name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      centrifugo:
        image: centrifugo/centrifugo:v3
        ports:
          - 8000:8000
        options: --entrypoint centrifugo \"--api_insecure\"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn run test
        env:
          CENTRIFUGO_HOST: "http://localhost:8000/api"

      - name: Run ESlint
        run: yarn lint
